pool:
  vmImage: 'Ubuntu 16.04'

trigger: none 

pr: none 

variables:
  location: eastus
  nodeCount: 3
  nodeSize: Standard_B2s
  # define 6 more variables: subscriptionId, spId, spSecret, spTenantId, aks and rg in the pipeline UI definition

steps:
- bash: /create-aks-cluster.sh
  displayName: 'create rg and aks'
  env:
      LOCATION: $(location)
      NODE_COUNT: $(nodeCount)
      NODE_SIZE: $(nodeSize)
      SUBSCRIPTION_ID: $(subscriptionId)
      SP_ID: $(spId)
      SP_SECRET: $(spSecret)
      SP_TENANT_ID: $(spTenantId)
      AKS: $(aks)
      RG: $(rg)
